//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp5.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tp5.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil Admin.
        /// </summary>
        public static string AdminIndexWeb {
            get {
                return ResourceManager.GetString("AdminIndexWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer la réservation.
        /// </summary>
        public static string ButtonConfirmReservation {
            get {
                return ResourceManager.GetString("ButtonConfirmReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string ButtonModif {
            get {
                return ResourceManager.GetString("ButtonModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un choix de menu.
        /// </summary>
        public static string ButtonNewMenuChoice {
            get {
                return ResourceManager.GetString("ButtonNewMenuChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à la page d&apos;accueil.
        /// </summary>
        public static string ButtonReturnHome {
            get {
                return ResourceManager.GetString("ButtonReturnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à la liste de réservations.
        /// </summary>
        public static string ButtonReturnListReservation {
            get {
                return ResourceManager.GetString("ButtonReturnListReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à la liste des choix de menu.
        /// </summary>
        public static string ButtonReturnToList {
            get {
                return ResourceManager.GetString("ButtonReturnToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Êtes-vous certain de vouloir supprimer ce menu?.
        /// </summary>
        public static string DeleteMenuQuestion {
            get {
                return ResourceManager.GetString("DeleteMenuQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un choix de menu.
        /// </summary>
        public static string DeleteMenuTitle {
            get {
                return ResourceManager.GetString("DeleteMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un menu.
        /// </summary>
        public static string DeleteMenuWeb {
            get {
                return ResourceManager.GetString("DeleteMenuWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer une réservation.
        /// </summary>
        public static string DeleteReservationTitle {
            get {
                return ResourceManager.GetString("DeleteReservationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details de la réservation.
        /// </summary>
        public static string DetailsReservation {
            get {
                return ResourceManager.GetString("DetailsReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réservation complétée avec succès.
        /// </summary>
        public static string DetailsReservationTitle {
            get {
                return ResourceManager.GetString("DetailsReservationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Courriel :.
        /// </summary>
        public static string E_Mail {
            get {
                return ResourceManager.GetString("E-Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allo Admin.
        /// </summary>
        public static string HomeAdminText {
            get {
                return ResourceManager.GetString("HomeAdminText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des menus.
        /// </summary>
        public static string ListMenuAdminWeb {
            get {
                return ResourceManager.GetString("ListMenuAdminWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lite des reservations.
        /// </summary>
        public static string ListReservationTitle {
            get {
                return ResourceManager.GetString("ListReservationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix de menu :.
        /// </summary>
        public static string MenuChoiceId {
            get {
                return ResourceManager.GetString("MenuChoiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LES CHOIX DE MENU.
        /// </summary>
        public static string MenuChoiceIndexAdmin {
            get {
                return ResourceManager.GetString("MenuChoiceIndexAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier un choix de menu.
        /// </summary>
        public static string ModifMenuTitle {
            get {
                return ResourceManager.GetString("ModifMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier un menu.
        /// </summary>
        public static string ModifMenuWeb {
            get {
                return ResourceManager.GetString("ModifMenuWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom :.
        /// </summary>
        public static string NameClient {
            get {
                return ResourceManager.GetString("NameClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RÉSERVATION EN LIGNE.
        /// </summary>
        public static string NavReservation {
            get {
                return ResourceManager.GetString("NavReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un menu.
        /// </summary>
        public static string NewMenuAdminWeb {
            get {
                return ResourceManager.GetString("NewMenuAdminWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un choix de menu.
        /// </summary>
        public static string NewMenuTitleAdmin {
            get {
                return ResourceManager.GetString("NewMenuTitleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle réservation.
        /// </summary>
        public static string NewReservationWeb {
            get {
                return ResourceManager.GetString("NewReservationWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de personne :.
        /// </summary>
        public static string NumberReservation {
            get {
                return ResourceManager.GetString("NumberReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LES RÉSERVATIONS.
        /// </summary>
        public static string ReservationIndexAdmin {
            get {
                return ResourceManager.GetString("ReservationIndexAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Au plaisir de vous voir bientôt.
        /// </summary>
        public static string SeeYouSoon {
            get {
                return ResourceManager.GetString("SeeYouSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;équipe.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci d&apos;avoir utiliser notre module de réservation en ligne..
        /// </summary>
        public static string ThanksMessage {
            get {
                return ResourceManager.GetString("ThanksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LES CHOIX DE MENU.
        /// </summary>
        public static string TitleListMenuAdmin {
            get {
                return ResourceManager.GetString("TitleListMenuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout d&apos;une réservation.
        /// </summary>
        public static string TitleReservation {
            get {
                return ResourceManager.GetString("TitleReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le id de menu existe déjà..
        /// </summary>
        public static string WarningIdDuplicate {
            get {
                return ResourceManager.GetString("WarningIdDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;identifiant de la reservation est introuvable..
        /// </summary>
        public static string WarningIdNotFound {
            get {
                return ResourceManager.GetString("WarningIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un courriel est requis.
        /// </summary>
        public static string WarningNeddMail {
            get {
                return ResourceManager.GetString("WarningNeddMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un nom est requis.
        /// </summary>
        public static string WarningNeedName {
            get {
                return ResourceManager.GetString("WarningNeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nombre de client doit être de plus de 0.
        /// </summary>
        public static string WarningNeedNumber {
            get {
                return ResourceManager.GetString("WarningNeedNumber", resourceCulture);
            }
        }
    }
}
