//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp5.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tp5.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;accès vous est interdit.
        /// </summary>
        public static string AccessDeniedChangeUserMsg {
            get {
                return ResourceManager.GetString("AccessDeniedChangeUserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accès refusé.
        /// </summary>
        public static string AccessDeniedMsg {
            get {
                return ResourceManager.GetString("AccessDeniedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil Admin.
        /// </summary>
        public static string AdminIndexWeb {
            get {
                return ResourceManager.GetString("AdminIndexWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à la page d&apos;acceuil.
        /// </summary>
        public static string BackToHomepage {
            get {
                return ResourceManager.GetString("BackToHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour vers la page de connexion.
        /// </summary>
        public static string BackToLoginPage {
            get {
                return ResourceManager.GetString("BackToLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string ButtonModif {
            get {
                return ResourceManager.GetString("ButtonModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un choix de menu.
        /// </summary>
        public static string ButtonNewMenuChoice {
            get {
                return ResourceManager.GetString("ButtonNewMenuChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à la liste de réservations.
        /// </summary>
        public static string ButtonReturnListReservation {
            get {
                return ResourceManager.GetString("ButtonReturnListReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à la liste des choix de menu.
        /// </summary>
        public static string ButtonReturnToList {
            get {
                return ResourceManager.GetString("ButtonReturnToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un nouveau compte.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Êtes-vous certain de vouloir supprimer ce menu?.
        /// </summary>
        public static string DeleteMenuQuestion {
            get {
                return ResourceManager.GetString("DeleteMenuQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un choix de menu.
        /// </summary>
        public static string DeleteMenuTitle {
            get {
                return ResourceManager.GetString("DeleteMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un menu.
        /// </summary>
        public static string DeleteMenuWeb {
            get {
                return ResourceManager.GetString("DeleteMenuWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer une réservation.
        /// </summary>
        public static string DeleteReservationTitle {
            get {
                return ResourceManager.GetString("DeleteReservationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Courriel :.
        /// </summary>
        public static string E_Mail {
            get {
                return ResourceManager.GetString("E-Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identification.
        /// </summary>
        public static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Model invalid.
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe est invalide.
        /// </summary>
        public static string InvalidUsernamePassword {
            get {
                return ResourceManager.GetString("InvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des menus.
        /// </summary>
        public static string ListMenuAdminWeb {
            get {
                return ResourceManager.GetString("ListMenuAdminWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lite des reservations.
        /// </summary>
        public static string ListReservationTitle {
            get {
                return ResourceManager.GetString("ListReservationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des membres.
        /// </summary>
        public static string MemberList {
            get {
                return ResourceManager.GetString("MemberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix de menu :.
        /// </summary>
        public static string MenuChoiceId {
            get {
                return ResourceManager.GetString("MenuChoiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LES CHOIX DE MENU.
        /// </summary>
        public static string MenuChoiceIndexAdmin {
            get {
                return ResourceManager.GetString("MenuChoiceIndexAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ModelLengthBetween.
        /// </summary>
        public static string ModelLengthBetween {
            get {
                return ResourceManager.GetString("ModelLengthBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ModelLengthLessThan.
        /// </summary>
        public static string ModelLengthLessThan {
            get {
                return ResourceManager.GetString("ModelLengthLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Model requis.
        /// </summary>
        public static string ModelRequired {
            get {
                return ResourceManager.GetString("ModelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier un choix de menu.
        /// </summary>
        public static string ModifMenuTitle {
            get {
                return ResourceManager.GetString("ModifMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier un menu.
        /// </summary>
        public static string ModifMenuWeb {
            get {
                return ResourceManager.GetString("ModifMenuWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom :.
        /// </summary>
        public static string NameClient {
            get {
                return ResourceManager.GetString("NameClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RÉSERVATION EN LIGNE.
        /// </summary>
        public static string NavReservation {
            get {
                return ResourceManager.GetString("NavReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un menu.
        /// </summary>
        public static string NewMenuAdminWeb {
            get {
                return ResourceManager.GetString("NewMenuAdminWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un choix de menu.
        /// </summary>
        public static string NewMenuTitleAdmin {
            get {
                return ResourceManager.GetString("NewMenuTitleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle réservation.
        /// </summary>
        public static string NewReservationWeb {
            get {
                return ResourceManager.GetString("NewReservationWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun membre n&apos;a été trouvé.
        /// </summary>
        public static string NoItemFound {
            get {
                return ResourceManager.GetString("NoItemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de personne :.
        /// </summary>
        public static string NumberReservation {
            get {
                return ResourceManager.GetString("NumberReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LES RÉSERVATIONS.
        /// </summary>
        public static string ReservationIndexAdmin {
            get {
                return ResourceManager.GetString("ReservationIndexAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se connecter.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se déconnecter.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LES CHOIX DE MENU.
        /// </summary>
        public static string TitleListMenuAdmin {
            get {
                return ResourceManager.GetString("TitleListMenuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout d&apos;une réservation.
        /// </summary>
        public static string TitleReservation {
            get {
                return ResourceManager.GetString("TitleReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nom d&apos;utilisateur.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le id de menu existe déjà..
        /// </summary>
        public static string WarningIdDuplicate {
            get {
                return ResourceManager.GetString("WarningIdDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;identifiant de la reservation est introuvable..
        /// </summary>
        public static string WarningIdNotFound {
            get {
                return ResourceManager.GetString("WarningIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un courriel est requis.
        /// </summary>
        public static string WarningNeddMail {
            get {
                return ResourceManager.GetString("WarningNeddMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un nom est requis.
        /// </summary>
        public static string WarningNeedName {
            get {
                return ResourceManager.GetString("WarningNeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nombre de client doit être de plus de 0.
        /// </summary>
        public static string WarningNeedNumber {
            get {
                return ResourceManager.GetString("WarningNeedNumber", resourceCulture);
            }
        }
    }
}
